apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cats-app
  template:
    metadata:
      labels:
        app: cats-app
    spec:
      containers:
      - name: cats-app
        image: 192.168.64.28:5100/cats-app:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cats-app
spec:
  selector:
    app: cats-app
  ports:
  - port: 80
    targetPort: 5000